
build : mkdir build &&cd build &&cmake..&&make

	  clean : rm
  - rf bin build

    style
  - fix : clang - format-- assume - filename =.clang - format
					      - i src
						  / main
						      .c

						      .PHONY : build clean
